[package]
name = "dybuk"
version = "0.1.0"
authors = ["Ticki <Ticki@users.noreply.github.com>"]

[dependencies]
term-painter = "*"
regex = "*"
unbug = { version = "0.3.0", features = ["enable"] }

[features]
default = []
Debug = ["unbug/enable"]
